### ISSUE TITLE
Current config for `otel-collector` results in duplicate label names

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/charts#121] opened 2022-12-28 17:46 UTC
This commit https://github.com/SigNoz/charts/commit/e6e32e5c0538c2e771e3e6a9e415c767bafcc400 introduced a change where the scraping the collector metrics is moved from `otel-collector-metrics` to `otel-collector`. The collector already adds `service_instance_id` and `service_name` to its data point attributes. And Prometheus receiver adds job name as `service.name` and instance as `service.instance.id`. When they are finally sanitised, they produce duplicates. While the duplicates are handled by overriding, the different order of values results in different end series. This wasn't an issue earlier because the `otel-collector-metrics` doesn't have the `resource_to_telemetry` conversion enabled to true.

**Comment by srikanthccv** [comment] 2022-12-29 05:32
@prashant-shahi

**Comment by srikanthccv** [comment] 2022-12-29 07:19
cc // @ankitnayan

**Comment by prashant-shahi** [comment] 2023-02-02 13:14
HotFix for the issue is merged already to the chart.

Ideal fix should be done in `conversion_to_telemetry` section of `clickhousemetricswrite` component.

**Closed by prashant-shahi** 2023-02-02 13:14 UTC
